# Generated by Django 6.0.5 on 2026-05-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('business_type', models.CharField(choices=[('ecommerce', 'Ecommerce'), ('service', 'Service'), ('hybrid', 'Hybrid')], max_length=50)),
                ('owner_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('company_description', models.TextField()),
                ('registration_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('modules', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
