# Generated by Django 6.0.5 on 2026-05-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('cake', 'Cake'), ('perfume', 'Perfume')], default='mobile', max_length=50),
        ),
    ]
