# Generated by Django 6.0.5 on 2026-06-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_trial_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.CharField(choices=[('trial', 'Free Trial'), ('monthly', 'Monthly'), ('six_month', 'Six Months'), ('yearly', 'Yearly')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
