# Generated by Django 6.0.5 on 2026-06-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_subscriptionpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='subscriptionpayment',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('six_month', 'Six Months'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=20),
        ),
    ]
