# Generated by Django 6.0.5 on 2026-06-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_remove_subscriptionpayment_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('ecommerce', 'Ecommerce'), ('service', 'Service'), ('hybrid', 'Hybrid')], default='ecommerce', max_length=50),
        ),
    ]
