# Generated by Django 6.0.5 on 2026-06-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_tenant_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='company_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
