# Generated by Django 6.0.5 on 2026-06-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='blocked_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='deleted_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
