# Generated by Django 6.0.5 on 2026-05-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
