# Generated by Django 6.0.5 on 2026-05-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_battery_capacity_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='battery_capacity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='charging_speed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='chipset',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='front_camera',
        ),
        migrations.RemoveField(
            model_name='product',
            name='front_video',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_core',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rear_camera',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rear_video',
        ),
        migrations.RemoveField(
            model_name='product',
            name='refresh_rate',
        ),
        migrations.AddField(
            model_name='product',
            name='business_type',
            field=models.CharField(choices=[('mobile', 'Mobile Store'), ('cake', 'Cake Shop'), ('perfume', 'Perfume Store')], default='mobile', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
